# Generated by Django 4.0.6 on 2022-09-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedChiName', models.CharField(max_length=150)),
                ('MedEngName', models.CharField(max_length=150)),
                ('Unit', models.CharField(max_length=150)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Number', models.AutoField(primary_key=True, serialize=False)),
                ('Memo', models.CharField(max_length=500, null=True)),
                ('History', models.CharField(max_length=500, null=True)),
                ('Phy', models.CharField(max_length=500, null=True)),
                ('Blood', models.CharField(max_length=500, null=True)),
                ('Image', models.CharField(max_length=500, null=True)),
                ('Diag', models.CharField(max_length=500, null=True)),
                ('Treat', models.CharField(max_length=500, null=True)),
                ('Drug', models.CharField(max_length=500, null=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Number', models.AutoField(primary_key=True, serialize=False)),
                ('Animal', models.CharField(max_length=150)),
                ('Species', models.CharField(max_length=150)),
                ('Sex', models.CharField(max_length=150)),
                ('Neuter', models.CharField(max_length=150)),
                ('Age', models.CharField(max_length=150, null=True)),
                ('Name', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=150)),
                ('Addr', models.CharField(max_length=150, null=True)),
                ('ID', models.CharField(max_length=150, null=True)),
                ('Doctor', models.CharField(max_length=150, null=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
